// <auto-generated>
// SpecDataGenerator에서 만들어진 파일입니다. 수정하지 마세요.
// Copyright (c) CookApps.
// 이진호(jhlee8@cookapps.com)
// </auto-generated>


/// 스킬 수치 타입
public enum SkillValueType
{
    NUMBER = 0,
    PERCENT = 1,
    TIME = 2,
    NONE = 3,
    RANGE = 4,
}

/// 스킬 타입
public enum SkillType
{
    ACTIVE = 0,
    ULTIMATE = 1,
    PASSIVE = 2,
}

/// 보상 타입
public enum RewardType
{
    Coin = 0,
    Exp = 1,
    WeaponBlueprint = 2,
    ArmorBlueprint = 3,
    Recovery = 4,
    Magnet = 5,
    GreenExpGem = 6,
    BlueExpGem = 7,
    YellowExpGem = 8,
    NONE = 9,
}

/// 몬스터 타입
public enum MonsterType
{
    NORMAL = 0,
    ELITE = 1,
    BOSS = 2,
}

/// 몬스터 이동 타입
public enum MonsterMoveType
{
    HOMING = 0,
    STRAIGHT = 1,
}

/// 몬스터 스폰 타입
public enum SpawnType
{
    ROUND = 0,
    CROWD = 1,
}

/// 몬스터 웨이브 타입
public enum WaveType
{
    NORMAL = 0,
    BOSS = 1,
    ELITE = 2,
}

/// 등급 타입
public enum GradeType
{
    LEGENDARY = 0,
    UNIQUE = 1,
    EPIC = 2,
    RARE = 3,
    NORMAL = 4,
}

/// 능력치 타입
public enum StatusType
{
    HP = 0,
    ATK = 1,
    ATKSPEED = 2,
    REVIVE = 3,
    MOVESPEED = 4,
    DCRDAMAGE = 5,
}

/// 장비 타입
public enum EquipType
{
    ARMOR = 0,
    WEAPON = 1,
}

/// 투사체 타입
public enum PrjType
{
    DRILL = 0,
    SHIELD = 1,
    BOMB = 2,
    LIGHTNING = 3,
    BUBBLE = 4,
    BOOMERANG = 5,
    MISSILE = 6,
    NONE = 7,
}

/// 몬스터 공격 타입
public enum MonsterAttackType
{
    MELEE = 0,
    RANGE = 1,
}

/// 보스 스킬 수치 타입
public enum BossSkillValueType
{
    TIME = 0,
    PRJNUMBER = 1,
    PRJRANGE = 2,
    DASHRANGE = 3,
    DASHSPEED = 4,
    NONE = 5,
}
